CREATE SCHEMA "app";
--> statement-breakpoint
CREATE TYPE "app"."customer_color" AS ENUM('green', 'yellow', 'red');--> statement-breakpoint
CREATE TYPE "app"."delivery_kind" AS ENUM('delivery', 'adjustment');--> statement-breakpoint
CREATE TYPE "app"."finance_entry_kind" AS ENUM('manual', 'delivery', 'supplier_payment', 'wage_payment');--> statement-breakpoint
CREATE TYPE "app"."order_status" AS ENUM('open', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "app"."password_scheme" AS ENUM('bcrypt', 'legacy_md5_bcrypt');--> statement-breakpoint
CREATE TYPE "app"."payment_method" AS ENUM('cash', 'card', 'back');--> statement-breakpoint
CREATE TYPE "app"."upload_status" AS ENUM('pending', 'uploaded');--> statement-breakpoint
CREATE TYPE "app"."user_role" AS ENUM('super_admin', 'user');--> statement-breakpoint
CREATE TABLE "app"."audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"store_id" integer,
	"user_id" integer,
	"action" varchar(64) NOT NULL,
	"entity_type" varchar(64) NOT NULL,
	"entity_id" integer,
	"summary" text DEFAULT '' NOT NULL,
	"details" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."audit_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."sessions" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" varchar(64),
	"user_agent" varchar(400),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."stores" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."stores_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"next_delivery_number" integer DEFAULT 1 NOT NULL,
	"next_order_number" integer DEFAULT 1 NOT NULL,
	"next_receipt_number" integer DEFAULT 1 NOT NULL,
	"legacy_key" varchar(32),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stores_legacyKey_unique" UNIQUE("legacy_key")
);
--> statement-breakpoint
ALTER TABLE "app"."stores" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."user_stores" (
	"user_id" integer NOT NULL,
	"store_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_stores_user_id_store_id_pk" PRIMARY KEY("user_id","store_id")
);
--> statement-breakpoint
ALTER TABLE "app"."user_stores" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(254) NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"password_hash" text NOT NULL,
	"password_scheme" "app"."password_scheme" DEFAULT 'bcrypt' NOT NULL,
	"role" "app"."user_role" DEFAULT 'user' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"last_login_at" timestamp with time zone,
	"password_changed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "app"."users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"name" text NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"tax_id" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"contact_person" text DEFAULT '' NOT NULL,
	"comment" text DEFAULT '' NOT NULL,
	"color" "app"."customer_color",
	"is_archived" boolean DEFAULT false NOT NULL,
	"legacy_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."customers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."product_price_changes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."product_price_changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"old_sale_price" numeric(18, 4) NOT NULL,
	"old_purchase_price" numeric(18, 4) NOT NULL,
	"new_sale_price" numeric(18, 4),
	"new_purchase_price" numeric(18, 4),
	"changed_on" date NOT NULL,
	"changed_by_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."product_price_changes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"supplier_id" integer,
	"name" text NOT NULL,
	"sale_price" numeric(18, 4) DEFAULT '0' NOT NULL,
	"purchase_price" numeric(18, 4) DEFAULT '0' NOT NULL,
	"stock_qty" integer DEFAULT 0 NOT NULL,
	"comment" text DEFAULT '' NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"legacy_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."products" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."suppliers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."suppliers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"name" text NOT NULL,
	"is_returns" boolean DEFAULT false NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"legacy_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."suppliers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."employees" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."employees_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"name" text NOT NULL,
	"wage_balance" numeric(18, 4) DEFAULT '0' NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"legacy_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."employees" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."finance_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."finance_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"name" text NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"legacy_table" varchar(32),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."finance_accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."finance_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."finance_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"entry_date" date NOT NULL,
	"kind" "app"."finance_entry_kind" DEFAULT 'manual' NOT NULL,
	"amount_in" numeric(18, 4) DEFAULT '0' NOT NULL,
	"amount_out" numeric(18, 4) DEFAULT '0' NOT NULL,
	"adjustment_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"note" text DEFAULT '' NOT NULL,
	"delivery_id" integer,
	"supplier_id" integer,
	"employee_id" integer,
	"legacy_id" integer,
	"legacy" jsonb,
	"created_by_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."finance_entries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."wage_accruals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."wage_accruals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer NOT NULL,
	"accrual_date" date NOT NULL,
	"amount" numeric(18, 4) NOT NULL,
	"comment" text DEFAULT '' NOT NULL,
	"created_by_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."wage_accruals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."deliveries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"customer_id" integer NOT NULL,
	"number" integer NOT NULL,
	"kind" "app"."delivery_kind" DEFAULT 'delivery' NOT NULL,
	"delivery_date" date NOT NULL,
	"total_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"paid_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"adjustment_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"payment_method" "app"."payment_method",
	"has_waybill" boolean,
	"discount_factor" numeric(6, 4),
	"upload_status" "app"."upload_status",
	"comment" text DEFAULT '' NOT NULL,
	"legacy" jsonb,
	"created_by_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."deliveries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."delivery_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."delivery_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"delivery_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"unit_price" numeric(18, 4) NOT NULL,
	"quantity" integer DEFAULT 0 NOT NULL,
	"gift_qty" integer DEFAULT 0 NOT NULL,
	"leftover_qty" integer DEFAULT 0 NOT NULL,
	"line_total" numeric(18, 4) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."delivery_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."order_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."order_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"unit_price" numeric(18, 4) NOT NULL,
	"quantity" integer DEFAULT 0 NOT NULL,
	"gift_qty" integer DEFAULT 0 NOT NULL,
	"leftover_qty" integer DEFAULT 0 NOT NULL,
	"line_total" numeric(18, 4) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."order_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"customer_id" integer NOT NULL,
	"number" integer NOT NULL,
	"order_date" date NOT NULL,
	"status" "app"."order_status" DEFAULT 'open' NOT NULL,
	"total_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"paid_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"debt_snapshot" numeric(18, 4) DEFAULT '0' NOT NULL,
	"payment_method" "app"."payment_method",
	"has_waybill" boolean,
	"discount_factor" numeric(6, 4),
	"upload_status" "app"."upload_status",
	"comment" text DEFAULT '' NOT NULL,
	"delivery_id" integer,
	"completed_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"legacy" jsonb,
	"created_by_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."stock_adjustments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."stock_adjustments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"quantity_delta" integer NOT NULL,
	"stock_before" integer NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"created_by_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."stock_adjustments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."stock_receipt_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."stock_receipt_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"receipt_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"quantity" integer NOT NULL,
	"unit_cost" numeric(18, 4) DEFAULT '0' NOT NULL,
	"stock_before" integer
);
--> statement-breakpoint
ALTER TABLE "app"."stock_receipt_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."stock_receipts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."stock_receipts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" integer NOT NULL,
	"supplier_id" integer,
	"number" integer NOT NULL,
	"receipt_date" date NOT NULL,
	"comment" text DEFAULT '' NOT NULL,
	"legacy_batch_id" bigint,
	"created_by_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."stock_receipts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "app"."audit_log" ADD CONSTRAINT "audit_log_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."audit_log" ADD CONSTRAINT "audit_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_stores" ADD CONSTRAINT "user_stores_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_stores" ADD CONSTRAINT "user_stores_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."customers" ADD CONSTRAINT "customers_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."product_price_changes" ADD CONSTRAINT "product_price_changes_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."product_price_changes" ADD CONSTRAINT "product_price_changes_changed_by_id_users_id_fk" FOREIGN KEY ("changed_by_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."products" ADD CONSTRAINT "products_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."products" ADD CONSTRAINT "products_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "app"."suppliers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."suppliers" ADD CONSTRAINT "suppliers_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."employees" ADD CONSTRAINT "employees_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."finance_accounts" ADD CONSTRAINT "finance_accounts_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."finance_entries" ADD CONSTRAINT "finance_entries_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."finance_entries" ADD CONSTRAINT "finance_entries_account_id_finance_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "app"."finance_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."finance_entries" ADD CONSTRAINT "finance_entries_delivery_id_deliveries_id_fk" FOREIGN KEY ("delivery_id") REFERENCES "app"."deliveries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."finance_entries" ADD CONSTRAINT "finance_entries_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "app"."suppliers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."finance_entries" ADD CONSTRAINT "finance_entries_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "app"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."finance_entries" ADD CONSTRAINT "finance_entries_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."wage_accruals" ADD CONSTRAINT "wage_accruals_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "app"."employees"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."wage_accruals" ADD CONSTRAINT "wage_accruals_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."deliveries" ADD CONSTRAINT "deliveries_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."deliveries" ADD CONSTRAINT "deliveries_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "app"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."deliveries" ADD CONSTRAINT "deliveries_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."delivery_items" ADD CONSTRAINT "delivery_items_delivery_id_deliveries_id_fk" FOREIGN KEY ("delivery_id") REFERENCES "app"."deliveries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."delivery_items" ADD CONSTRAINT "delivery_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."order_items" ADD CONSTRAINT "order_items_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "app"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."order_items" ADD CONSTRAINT "order_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."orders" ADD CONSTRAINT "orders_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."orders" ADD CONSTRAINT "orders_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "app"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."orders" ADD CONSTRAINT "orders_delivery_id_deliveries_id_fk" FOREIGN KEY ("delivery_id") REFERENCES "app"."deliveries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."orders" ADD CONSTRAINT "orders_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_adjustments" ADD CONSTRAINT "stock_adjustments_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_adjustments" ADD CONSTRAINT "stock_adjustments_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_adjustments" ADD CONSTRAINT "stock_adjustments_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_receipt_items" ADD CONSTRAINT "stock_receipt_items_receipt_id_stock_receipts_id_fk" FOREIGN KEY ("receipt_id") REFERENCES "app"."stock_receipts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_receipt_items" ADD CONSTRAINT "stock_receipt_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "app"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_receipts" ADD CONSTRAINT "stock_receipts_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "app"."stores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_receipts" ADD CONSTRAINT "stock_receipts_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "app"."suppliers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."stock_receipts" ADD CONSTRAINT "stock_receipts_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "app"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_log_store_id_created_at_index" ON "app"."audit_log" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_log_entity_type_entity_id_index" ON "app"."audit_log" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "sessions_user_id_index" ON "app"."sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_expires_at_index" ON "app"."sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "user_stores_store_id_index" ON "app"."user_stores" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "customers_store_id_is_archived_index" ON "app"."customers" USING btree ("store_id","is_archived");--> statement-breakpoint
CREATE UNIQUE INDEX "customers_store_id_legacy_id_index" ON "app"."customers" USING btree ("store_id","legacy_id");--> statement-breakpoint
CREATE INDEX "product_price_changes_product_id_index" ON "app"."product_price_changes" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "products_store_id_is_archived_index" ON "app"."products" USING btree ("store_id","is_archived");--> statement-breakpoint
CREATE INDEX "products_supplier_id_index" ON "app"."products" USING btree ("supplier_id");--> statement-breakpoint
CREATE UNIQUE INDEX "products_store_id_legacy_id_index" ON "app"."products" USING btree ("store_id","legacy_id");--> statement-breakpoint
CREATE INDEX "suppliers_store_id_is_archived_index" ON "app"."suppliers" USING btree ("store_id","is_archived");--> statement-breakpoint
CREATE UNIQUE INDEX "suppliers_store_id_legacy_id_index" ON "app"."suppliers" USING btree ("store_id","legacy_id");--> statement-breakpoint
CREATE INDEX "employees_store_id_is_archived_index" ON "app"."employees" USING btree ("store_id","is_archived");--> statement-breakpoint
CREATE INDEX "finance_accounts_store_id_index" ON "app"."finance_accounts" USING btree ("store_id");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_accounts_one_default_per_store" ON "app"."finance_accounts" USING btree ("store_id") WHERE "app"."finance_accounts"."is_default";--> statement-breakpoint
CREATE INDEX "finance_entries_account_id_id_index" ON "app"."finance_entries" USING btree ("account_id","id");--> statement-breakpoint
CREATE INDEX "finance_entries_store_id_entry_date_index" ON "app"."finance_entries" USING btree ("store_id","entry_date");--> statement-breakpoint
CREATE INDEX "finance_entries_supplier_id_index" ON "app"."finance_entries" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "finance_entries_employee_id_index" ON "app"."finance_entries" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX "finance_entries_delivery_id_index" ON "app"."finance_entries" USING btree ("delivery_id");--> statement-breakpoint
CREATE INDEX "wage_accruals_employee_id_index" ON "app"."wage_accruals" USING btree ("employee_id");--> statement-breakpoint
CREATE UNIQUE INDEX "deliveries_store_id_number_index" ON "app"."deliveries" USING btree ("store_id","number");--> statement-breakpoint
CREATE INDEX "deliveries_customer_id_id_index" ON "app"."deliveries" USING btree ("customer_id","id");--> statement-breakpoint
CREATE INDEX "deliveries_store_id_delivery_date_index" ON "app"."deliveries" USING btree ("store_id","delivery_date");--> statement-breakpoint
CREATE INDEX "delivery_items_delivery_id_index" ON "app"."delivery_items" USING btree ("delivery_id");--> statement-breakpoint
CREATE INDEX "delivery_items_product_id_index" ON "app"."delivery_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "order_items_order_id_index" ON "app"."order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "order_items_product_id_index" ON "app"."order_items" USING btree ("product_id");--> statement-breakpoint
CREATE UNIQUE INDEX "orders_store_id_number_index" ON "app"."orders" USING btree ("store_id","number");--> statement-breakpoint
CREATE INDEX "orders_store_id_status_id_index" ON "app"."orders" USING btree ("store_id","status","id");--> statement-breakpoint
CREATE INDEX "orders_customer_id_index" ON "app"."orders" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "stock_adjustments_product_id_index" ON "app"."stock_adjustments" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "stock_adjustments_store_id_created_at_index" ON "app"."stock_adjustments" USING btree ("store_id","created_at");--> statement-breakpoint
CREATE INDEX "stock_receipt_items_receipt_id_index" ON "app"."stock_receipt_items" USING btree ("receipt_id");--> statement-breakpoint
CREATE INDEX "stock_receipt_items_product_id_index" ON "app"."stock_receipt_items" USING btree ("product_id");--> statement-breakpoint
CREATE UNIQUE INDEX "stock_receipts_store_id_number_index" ON "app"."stock_receipts" USING btree ("store_id","number");--> statement-breakpoint
CREATE INDEX "stock_receipts_supplier_id_index" ON "app"."stock_receipts" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "stock_receipts_store_id_receipt_date_index" ON "app"."stock_receipts" USING btree ("store_id","receipt_date");